### ISSUE TITLE
Drag and Drop Feature not working

### ISSUE THREAD

**Issue by ayearwood81** [Podcast-Planner/podcast-planner#63]
Haven't looked at the code yet to make sure that this is indeed a feature in the final product, but read in the Read Me it says that the playlists can be dragged and dropped to reorder them in my saved playlists but I wasn't able to do that!

**Comment by luckyNoodles** [comment]
This is a known issue. The Desktop drag and drop works but the Touch is a planned future release.

**Comment by ayearwood81** [comment]
Oh, I was actually only looking at it on desktop and it wasn't working for
me!
